min_circle_size = 1.0
max_circle_size = 5.199999809265137
audio_enabled = false
is_fullscreen = true
jiggle = 10.0
mouse_repel_force = 2.0
mouse_attract_force = 0.15000000596046448
mouse_attract_distance = 100.0
medium_viscosity = 100.0
num_circles = 1000
num_circles_ui = 1000.0
gravity_enabled = false
particle_repel_force = 30.0
allow_ball_intersection = true
draw_velocities = false
boids = true
boids_box_size = 50.0
separation_distance = 10.0
separation_weight = 0.10000000149011612
alignment_weight = 0.6610687375068665
cohesion_weight = 0.3431297838687897
avoid_walls_weight = 0.10351145267486572
avoid_walls_distance = 100.0
boid_amount = 2.8702290058135986
max_velocity = 140.91603088378906
