min_circle_size = 5.0
max_circle_size = 25.0
audio_enabled = false
is_fullscreen = true
jiggle = 3.0
mouse_repel_force = 2.0
mouse_attract_force = 0.15000000596046448
mouse_attract_distance = 100.0
medium_viscosity = 100.0
num_circles = 1000
num_circles_ui = 1000.0
gravity_enabled = false
particle_repel_force = 30.0
allow_ball_intersection = true
draw_velocities = false
boids = true
boids_box_size = 94.656494140625
separation_distance = 56.374046325683594
separation_weight = 5.0
alignment_weight = 0.3805343508720398
cohesion_weight = 1.0
avoid_walls_weight = 0.030572518706321716
boid_amount = 10.0
max_velocity = 140.91603088378906
