name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to tag and release as (should match Cargo.toml)
        required: true
        type: string

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check version matches toml
        run: |
          VERSION=$(grep -oP '^version = "\K[^"]+' Cargo.toml)
          if [ "$VERSION" != "${{ github.event.inputs.version }}" ]; then
            echo "Error: Version in Cargo.toml ($VERSION) does not match input version (${{ github.event.inputs.version }})"
            exit 1
          fi
      - name: Build for Linux
        run: |
          cargo build --release
      - name: Package for Linux
        run: |
          mkdir -p release/linux
          cp target/release/jiggleballs release/linux
          cp config.toml release/linux
          cp OfficeCodePro-Regular.ttf release/linux
          tar czf Linux-x86_64.tar.gz release/linux/
      - name: Create release
        id: create_release
        uses: dothq/tag-and-release-and-upload@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: v${{ github.event.inputs.version }}
          body_path: release-body.md
          assets: '[ "Linux-x86_64.tar.gz" ]'
          overwrite: false # set to true if you need to replace a release's assets for some reason

