name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to tag and release as (should match Cargo.toml)
        required: true
        type: string

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check version matches toml
        run: |
          VERSION=$(grep -oP '^version = "\K[^"]+' Cargo.toml)
          if [ "$VERSION" != "${{ github.event.inputs.version }}" ]; then
            echo "Error: Version in Cargo.toml ($VERSION) does not match input version (${{ github.event.inputs.version }})"
            exit 1
          fi
      - name: Build for Linux
        run: |
          cargo build --release
      - name: Package for Linux
        run: |
          mkdir -p release/linux
          cp target/release/jiggleballs release/linux
          cp config.toml release/linux
          cp OfficeCodePro-Regular.ttf release/linux
      - name: Create release
        id: create_release
        uses: avakar/tag-and-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload binaries
        id: upload_binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: release/
        if: success()

